import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { notFound } from "next/navigation";

import { routing } from '@/i18n/routing';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

// export async function generateMetadata({
//   params
// }: {
//   params: Promise<{ locale: string }>;
// }): Promise<Metadata> {
//   const { locale } = await params;
//   if (!hasLocale(routing.locales, locale)) {
//     notFound();
//   }

//   const isJapanese = locale === "ja";

//   return {
//     title: "Sameshima Coffee Roastery Angler",
//     description: isJapanese
//       ? "大阪京橋にある自家焙煎Cafe&Bar"
//       : "Home-roasted coffee Cafe&Bar in Kyobashi, Osaka",
//     alternates: {
//       canonical: isJapanese ? "/ja" : "/en",
//       languages: {
//         en: "/en",
//         ja: "/ja",
//       },
//     },
//     openGraph: {
//       url: isJapanese ? "https://angler.com/ja" : "https://angler.com/en",
//       // images: [
//       //   {
//       //     url: isJapanese ? "https://example.com/og-image-ja.jpg" : "https://example.com/og-image-en.jpg",
//       //     width: 1200,
//       //     height: 630,
//       //     alt: isJapanese ? "ランディングページSEOのコツ" : "SEO Tips for Landing Pages",
//       //   },
//       // ],
//     },
//     twitter: {
//       card: "summary_large_image",
//       site: "@angler",
//       title: "Sameshima Coffee Roastery Angler",
//       description: isJapanese
//         ? "大阪京橋にある自家焙煎Cafe&Bar"
//         : "Home-roasted coffee Cafe&Bar in Kyobashi, Osaka",
//       // images: ["https://example.com/og-image.jpg"],
//     },
//     metadataBase: new URL("https://angler.com"),
//     robots: {
//       index: true,
//       follow: true,
//     },
//     icons: {
//       icon: "/images/favicon.jpg",
//     }
//     // verification: {
//     //   google: "your-google-site-verification-code",
//     // },
//   };
// }